services:
  postgres:
    image: postgres:16-alpine
    container_name: camba-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: camba
      POSTGRES_PASSWORD: camba123
      POSTGRES_DB: camba
    ports:
      - "5432:5432"
    volumes:
      - camba_pg_data:/var/lib/postgresql/data

volumes:
  camba_pg_data:
