import type { LevelSupplement } from "./merge";
import { gapsFromRows, listeningFromRows, readingFromSets, speakingsFromRows, writingsFromRows } from "./helpers";
import { FCE_LISTENING_ROWS } from "./data/fce-listening";

const reading = readingFromSets([
  {
    title: "Carbon capture pilot",
    passage: "Engineers are testing a carbon capture unit at a regional power station. Early data suggests emissions could fall by eighteen per cent, though critics argue costs remain too high for widespread use.",
    questions: [
      { question: "Where is the unit being tested?", options: ["At a school","At a regional power station","In a museum","On a farm"], answer: "At a regional power station" },
      { question: "By how much could emissions fall?", options: ["Five per cent","Eighteen per cent","Fifty per cent","None"], answer: "Eighteen per cent" },
      { question: "What do critics say?", options: ["Costs are too high","It is free","It is perfect","It is illegal"], answer: "Costs are too high" },
      { question: "What is being captured?", options: ["Water","Carbon","Noise","Light"], answer: "Carbon" },
      { question: "What stage is the project?", options: ["Testing/pilot","Closed","Finished worldwide","Cancelled"], answer: "Testing/pilot" },
    ],
  },
  {
    title: "Medieval manuscript",
    passage: "Researchers discovered a medieval manuscript in a private archive. Specialists are using imaging technology to read damaged pages. Publication is expected within two years.",
    questions: [
      { question: "What was discovered?", options: ["A coin","A medieval manuscript","A car","A statue"], answer: "A medieval manuscript" },
      { question: "Where was it found?", options: ["In a shop","In a private archive","On a beach","At school"], answer: "In a private archive" },
      { question: "What technology is used?", options: ["Imaging technology","Drones only","Robots only","None"], answer: "Imaging technology" },
      { question: "When is publication expected?", options: ["Within two years","Tomorrow","In twenty years","Never"], answer: "Within two years" },
      { question: "What is damaged?", options: ["Pages","The building only","Computers","Roads"], answer: "Pages" },
    ],
  },
  {
    title: "Remote healthcare",
    passage: "A trial offers video consultations for minor illnesses in rural areas. Patients save travel time, but doctors warn that physical examinations are sometimes necessary.",
    questions: [
      { question: "Who is the trial for?", options: ["Urban areas only","Rural areas","Airports","Schools"], answer: "Rural areas" },
      { question: "What do patients save?", options: ["Travel time","Money only","Food","Books"], answer: "Travel time" },
      { question: "What do doctors warn about?", options: ["Physical examinations may be necessary","All care is perfect","No technology works","Hospitals will close"], answer: "Physical examinations may be necessary" },
      { question: "What kind of illnesses?", options: ["Minor illnesses","Only surgery","Only broken bones","None"], answer: "Minor illnesses" },
      { question: "How are consultations done?", options: ["By video","By letter only","In person only","By phone only"], answer: "By video" },
    ],
  },
]);

const uoe = gapsFromRows([
  ["Were Tom to accept, the photography prog", "Were Tom to accept, the photography programme ___ expand next year.", "would"],
  ["No sooner", "No sooner ___ the environment talk begun than the fire alarm rang.", "had"],
  ["Ben is thought", "Ben is thought ___ (discover) a new physics method.", "to have discovered"],
  ["Seldom", "Seldom ___ such archaeology results in the station.", "do we see"],
  ["If Sara", "If Sara ___ (study) harder, the photography results would improve.", "studied"],
  ["Not until 2:30", "Not until 2:30 ___ the journalism lecture begin.", "did"],
  ["Emma is believed", "Emma is believed ___ (win) the regional physics prize.", "to have won"],
  ["Little", "Little ___ that the café would close so soon.", "did we know"],
  ["The report,", "The report, ___ (publish) last week, mentions biology.", "published"],
  ["Noah would rather", "Noah would rather ___ (work) on space than attend the meeting.", "work"],
  ["Scarcely", "Scarcely ___ Minh finished the engineering report when the alarm sounded.", "had"],
  ["Had Lucas known about poetry, Lucas", "Had Lucas known about poetry, Lucas ___ (apply) earlier.", "would have applied"],
  ["Were Sophie to accept, the gardening pro", "Were Sophie to accept, the gardening programme ___ expand next year.", "would"],
  ["No sooner", "No sooner ___ the weather talk begun than the fire alarm rang.", "had"],
  ["Chloe is thought", "Chloe is thought ___ (discover) a new astronomy method.", "to have discovered"],
  ["Seldom", "Seldom ___ such history results in the hospital.", "do we see"],
  ["If Lan", "If Lan ___ (study) harder, the gardening results would improve.", "studied"],
  ["Not until 5:00", "Not until 5:00 ___ the medicine lecture begin.", "did"],
  ["Linh is believed", "Linh is believed ___ (win) the regional astronomy prize.", "to have won"],
  ["Little", "Little ___ that the airport would close so soon.", "did we know"],
  ["The report,", "The report, ___ (publish) last week, mentions sociology.", "published"],
  ["Anna would rather", "Anna would rather ___ (work) on theatre than attend the meeting.", "work"],
  ["Scarcely", "Scarcely ___ Leo finished the recycling report when the alarm sounded.", "had"],
  ["Had Lily known about marketing, Lily", "Had Lily known about marketing, Lily ___ (apply) earlier.", "would have applied"],
  ["Were Sara to accept, the architecture pr", "Were Sara to accept, the architecture programme ___ expand next year.", "would"],
  ["No sooner", "No sooner ___ the geography talk begun than the fire alarm rang.", "had"],
  ["Emma is thought", "Emma is thought ___ (discover) a new science method.", "to have discovered"],
  ["Seldom", "Seldom ___ such languages results in the beach.", "do we see"],
  ["If Mia", "If Mia ___ (study) harder, the architecture results would improve.", "studied"],
  ["Not until 7:30", "Not until 7:30 ___ the football lecture begin.", "did"],
  ["Olivia is believed", "Olivia is believed ___ (win) the regional science prize.", "to have won"],
  ["Little", "Little ___ that the cinema would close so soon.", "did we know"],
  ["The report,", "The report, ___ (publish) last week, mentions volunteering.", "published"],
  ["Daniel would rather", "Daniel would rather ___ (work) on nutrition than attend the meeting.", "work"],
  ["Scarcely", "Scarcely ___ An finished the reading report when the alarm sounded.", "had"],
  ["Had Minh known about environment, Minh", "Had Minh known about environment, Minh ___ (apply) earlier.", "would have applied"],
  ["Were Lan to accept, the law programme", "Were Lan to accept, the law programme ___ expand next year.", "would"],
  ["No sooner", "No sooner ___ the archaeology talk begun than the fire alarm rang.", "had"],
  ["Linh is thought", "Linh is thought ___ (discover) a new films method.", "to have discovered"],
  ["Seldom", "Seldom ___ such biology results in the park.", "do we see"],
  ["If Tom", "If Tom ___ (study) harder, the law results would improve.", "studied"],
  ["Not until 8:15", "Not until 8:15 ___ the swimming lecture begin.", "did"],
  ["Ben is believed", "Ben is believed ___ (win) the regional films prize.", "to have won"],
  ["Little", "Little ___ that the zoo would close so soon.", "did we know"],
  ["The report,", "The report, ___ (publish) last week, mentions cycling.", "published"],
  ["Jack would rather", "Jack would rather ___ (work) on technology than attend the meeting.", "work"],
  ["Scarcely", "Scarcely ___ Lucas finished the space report when the alarm sounded.", "had"],
  ["Had Leo known about weather, Leo", "Had Leo known about weather, Leo ___ (apply) earlier.", "would have applied"],
  ["Were Mia to accept, the music programme", "Were Mia to accept, the music programme ___ expand next year.", "would"],
  ["No sooner", "No sooner ___ the history talk begun than the fire alarm rang.", "had"],
  ["Olivia is thought", "Olivia is thought ___ (discover) a new economics method.", "to have discovered"],
  ["Seldom", "Seldom ___ such sociology results in the supermarket.", "do we see"],
  ["If Sophie", "If Sophie ___ (study) harder, the music results would improve.", "studied"],
  ["Not until 10:45", "Not until 10:45 ___ the fashion lecture begin.", "did"],
  ["Chloe is believed", "Chloe is believed ___ (win) the regional economics prize.", "to have won"],
  ["Little", "Little ___ that the library would close so soon.", "did we know"],
  ["The report,", "The report, ___ (publish) last week, mentions robotics.", "published"],
  ["Huy would rather", "Huy would rather ___ (work) on festivals than attend the meeting.", "work"],
  ["Scarcely", "Scarcely ___ Lily finished the theatre report when the alarm sounded.", "had"],
  ["Had An known about geography, An", "Had An known about geography, An ___ (apply) earlier.", "would have applied"],
  ["Were Tom to accept, the drama programme", "Were Tom to accept, the drama programme ___ expand next year.", "would"],
  ["No sooner", "No sooner ___ the languages talk begun than the fire alarm rang.", "had"],
  ["Ben is thought", "Ben is thought ___ (discover) a new psychology method.", "to have discovered"],
  ["Seldom", "Seldom ___ such volunteering results in the station.", "do we see"],
  ["If Sara", "If Sara ___ (study) harder, the drama results would improve.", "studied"],
  ["Not until 2:30", "Not until 2:30 ___ the design lecture begin.", "did"],
  ["Emma is believed", "Emma is believed ___ (win) the regional psychology prize.", "to have won"],
  ["The report,", "The report, ___ (publish) last week, mentions philosophy.", "published"],
  ["Noah would rather", "Noah would rather ___ (work) on literature than attend the meeting.", "work"],
  ["Scarcely", "Scarcely ___ Minh finished the nutrition report when the alarm sounded.", "had"],
]);

const writing = writingsFromRows([
  ["Story start", "Write a story that begins: 'When I opened the door, I couldn't believe my eyes.'\n\nWrite 140–190 words.", 190, "B2 First writing."],
  ["Blog post", "Write a blog post about a club you enjoy.\n\nWrite 140–190 words.", 190, "B2 First writing."],
  ["Email plans", "Write an email to a friend about plans for next month.\n\nWrite 140–190 words.", 190, "B2 First writing."],
  ["Opinion", "Write about whether students should wear uniform.\n\nWrite 140–190 words.", 190, "B2 First writing."],
  ["Trip report", "Write about a school trip you enjoyed.\n\nWrite 140–190 words.", 190, "B2 First writing."],
  ["Film message", "Write a message recommending a film to a friend.\n\nWrite 140–190 words.", 190, "B2 First writing."],
  ["Environment", "Write about one thing your school does to help the environment.\n\nWrite 140–190 words.", 190, "B2 First writing."],
  ["Competition", "Write about a competition you entered.\n\nWrite 140–190 words.", 190, "B2 First writing."],
  ["Invitation reply", "Reply to an invitation. You can come but will be late.\n\nWrite 140–190 words.", 190, "B2 First writing."],
  ["New hobby", "Write about a new hobby you started this year.\n\nWrite 140–190 words.", 190, "B2 First writing."],
]);

const speaking = speakingsFromRows([
  ["School life", "Compare learning at school and learning online. Which do you prefer?", 15, 90],
  ["Role model", "Describe someone you admire. What have they achieved?", 15, 90],
  ["Technology", "How do you use technology for homework and hobbies?", 15, 90],
  ["Travel", "Tell me about an interesting place you visited.", 15, 90],
  ["Future", "What job would you like in the future? Why?", 15, 90],
  ["Environment", "What can young people do to reduce plastic waste?", 15, 90],
  ["Books films", "Do you prefer reading books or watching films? Why?", 15, 90],
  ["Friends", "What makes a good friend?", 15, 90],
  ["Sports", "Describe a sport or game you enjoy playing.", 15, 90],
  ["English", "Why are you learning English? How do you practise?", 15, 90],
]);

export const FCE_SUPPLEMENT: LevelSupplement = {
  reading,
  listening: listeningFromRows(FCE_LISTENING_ROWS),
  writing,
  speaking,
  uoe,
};
