import type { LevelSupplement } from "./merge";
import { gapsFromRows, listeningFromRows, readingFromSets, speakingsFromRows, writingsFromRows } from "./helpers";
import { KET_LISTENING_ROWS } from "./data/ket-listening";

const reading = readingFromSets([
  {
    title: "Community cinema",
    passage: "The old town cinema reopened after repairs. It shows family films on Saturdays and classic films on Monday evenings. Tickets are cheaper for students before six o'clock.",
    questions: [
      { question: "When does it show family films?", options: ["Fridays","Saturdays","Sundays","Every day"], answer: "Saturdays" },
      { question: "When are classic films shown?", options: ["Monday evenings","Tuesday mornings","Wednesday afternoons","Never"], answer: "Monday evenings" },
      { question: "Who gets cheaper tickets before six?", options: ["Teachers","Students","Drivers","Everyone"], answer: "Students" },
      { question: "Why did it reopen?", options: ["After repairs","After a holiday","After moving","After closing forever"], answer: "After repairs" },
      { question: "What kind of place is it?", options: ["A shop","A cinema","A school","A farm"], answer: "A cinema" },
    ],
  },
  {
    title: "Running club",
    passage: "Running club meets at the park on Tuesday and Thursday mornings before school. Members warm up together and run two kilometres. New runners are always welcome.",
    questions: [
      { question: "Where does the club meet?", options: ["At the park","In the library","At the beach","In class"], answer: "At the park" },
      { question: "When does it meet?", options: ["Monday only","Tuesday and Thursday mornings","Weekends only","Every night"], answer: "Tuesday and Thursday mornings" },
      { question: "How far do they run?", options: ["One kilometre","Two kilometres","Ten kilometres","One metre"], answer: "Two kilometres" },
      { question: "Are new runners welcome?", options: ["No","Yes","Only teachers","Only on Fridays"], answer: "Yes" },
      { question: "What do they do first?", options: ["Sleep","Warm up together","Eat lunch","Watch TV"], answer: "Warm up together" },
    ],
  },
]);

const uoe = gapsFromRows([
  ["Tom is good", "Tom is good ___ playing debate.", "at"],
  ["Grammar 2", "We ___ (not see) Emma since Monday.", "haven't seen"],
  ["This photography lesson is", "This photography lesson is ___ (easy) than the last one.", "easier"],
  ["If you", "If you ___ ( hurry ), you'll catch the bus.", "hurry"],
  ["Grammar 5", "Sara ___ (write) an email about art now.", "is writing"],
  ["Grammar 6", "How ___ entrepreneurship classes do you have?", "many"],
  ["Grammar 7", "Emma ___ (not finish) the technology homework yet.", "hasn't finished"],
  ["Grammar 8", "If it ___ (rain), we'll stay at the café.", "rains"],
  ["Mia is", "Mia is ___ (interested) in geography.", "interested"],
  ["How much", "How much ___ this music book cost?", "does"],
  ["Grammar 11", "Minh ___ (study) gardening when I called.", "was studying"],
  ["We have lived near the cinema", "We have lived near the cinema ___ 2019.", "since"],
  ["Sophie usually", "Sophie usually ___ (walk) to the beach.", "walks"],
  ["There isn't", "There isn't ___ rice left.", "any"],
  ["Chloe is good", "Chloe is good ___ playing law.", "at"],
  ["Grammar 16", "We ___ (not see) Tom since Monday.", "haven't seen"],
  ["This films lesson is", "This films lesson is ___ (easy) than the last one.", "easier"],
  ["Grammar 18", "Linh ___ (write) an email about fashion now.", "is writing"],
  ["Grammar 19", "How ___ technology classes do you have?", "many"],
  ["Grammar 20", "Tom ___ (not finish) the space homework yet.", "hasn't finished"],
  ["Grammar 21", "If it ___ (rain), we'll stay at the supermarket.", "rains"],
  ["Ben is", "Ben is ___ (interested) in marketing.", "interested"],
  ["How much", "How much ___ this gardening book cost?", "does"],
  ["Grammar 24", "Noah ___ (study) economics when I called.", "was studying"],
  ["We have lived near the hospital", "We have lived near the hospital ___ 2019.", "since"],
  ["Emma usually", "Emma usually ___ (walk) to the museum.", "walks"],
  ["There isn't", "There isn't ___ chicken left.", "any"],
  ["Mia is good", "Mia is good ___ playing photography.", "at"],
  ["Grammar 29", "We ___ (not see) Chloe since Monday.", "haven't seen"],
  ["This physics lesson is", "This physics lesson is ___ (easy) than the last one.", "easier"],
  ["Sophie", "Sophie ___ (write) an email about medicine now.", "is writing"],
  ["Grammar 32", "How ___ space classes do you have?", "many"],
  ["Grammar 33", "Chloe ___ (not finish) the engineering homework yet.", "hasn't finished"],
  ["Grammar 34", "If it ___ (rain), we'll stay at the garden.", "rains"],
  ["Lan is", "Lan is ___ (interested) in art.", "interested"],
  ["How much", "How much ___ this economics book cost?", "does"],
  ["Grammar 37", "Lily ___ (study) astronomy when I called.", "was studying"],
  ["We have lived near the market", "We have lived near the market ___ 2019.", "since"],
  ["Tom usually", "Tom usually ___ (walk) to the library.", "walks"],
  ["There isn't", "There isn't ___ banana left.", "any"],
  ["Ben is good", "Ben is good ___ playing films.", "at"],
  ["Grammar 42", "We ___ (not see) Mia since Monday.", "haven't seen"],
  ["This entrepreneurship lesson is", "This entrepreneurship lesson is ___ (easy) than the last one.", "easier"],
  ["Grammar 44", "Emma ___ (write) an email about cooking now.", "is writing"],
  ["Grammar 45", "How ___ engineering classes do you have?", "many"],
  ["Grammar 46", "Mia ___ (not finish) the music homework yet.", "hasn't finished"],
  ["Grammar 47", "If it ___ (rain), we'll stay at the airport.", "rains"],
  ["Olivia is", "Olivia is ___ (interested) in fashion.", "interested"],
  ["How much", "How much ___ this astronomy book cost?", "does"],
  ["Grammar 50", "Huy ___ (study) travel when I called.", "was studying"],
  ["We have lived near the zoo", "We have lived near the zoo ___ 2019.", "since"],
  ["Chloe usually", "Chloe usually ___ (walk) to the park.", "walks"],
  ["There isn't", "There isn't ___ soup left.", "any"],
  ["Lan is good", "Lan is good ___ playing physics.", "at"],
  ["Grammar 55", "We ___ (not see) Ben since Monday.", "haven't seen"],
  ["This technology lesson is", "This technology lesson is ___ (easy) than the last one.", "easier"],
  ["Grammar 57", "Tom ___ (write) an email about cycling now.", "is writing"],
  ["Grammar 58", "How ___ music classes do you have?", "many"],
  ["Grammar 59", "Ben ___ (not finish) the gardening homework yet.", "hasn't finished"],
  ["Grammar 60", "If it ___ (rain), we'll stay at the station.", "rains"],
  ["Sara is", "Sara is ___ (interested) in medicine.", "interested"],
  ["How much", "How much ___ this travel book cost?", "does"],
  ["Grammar 63", "Lucas ___ (study) festivals when I called.", "was studying"],
  ["We have lived near the beach", "We have lived near the beach ___ 2019.", "since"],
  ["Mia usually", "Mia usually ___ (walk) to the school.", "walks"],
  ["There isn't", "There isn't ___ cake left.", "any"],
  ["Olivia is good", "Olivia is good ___ playing entrepreneurship.", "at"],
  ["Grammar 68", "We ___ (not see) Lan since Monday.", "haven't seen"],
  ["This space lesson is", "This space lesson is ___ (easy) than the last one.", "easier"],
  ["Grammar 70", "Chloe ___ (write) an email about biology now.", "is writing"],
]);

const writing = writingsFromRows([
  ["Story start", "Write a story that begins: 'When I opened the door, I couldn't believe my eyes.'\n\nWrite 25–35 words.", 35, "A2 Key writing."],
  ["Blog post", "Write a blog post about a club you enjoy.\n\nWrite 25–35 words.", 35, "A2 Key writing."],
  ["Email plans", "Write an email to a friend about plans for next month.\n\nWrite 25–35 words.", 35, "A2 Key writing."],
  ["Opinion", "Write about whether students should wear uniform.\n\nWrite 25–35 words.", 35, "A2 Key writing."],
  ["Trip report", "Write about a school trip you enjoyed.\n\nWrite 25–35 words.", 35, "A2 Key writing."],
  ["Film message", "Write a message recommending a film to a friend.\n\nWrite 25–35 words.", 35, "A2 Key writing."],
  ["Environment", "Write about one thing your school does to help the environment.\n\nWrite 25–35 words.", 35, "A2 Key writing."],
  ["Competition", "Write about a competition you entered.\n\nWrite 25–35 words.", 35, "A2 Key writing."],
  ["Invitation reply", "Reply to an invitation. You can come but will be late.\n\nWrite 25–35 words.", 35, "A2 Key writing."],
  ["New hobby", "Write about a new hobby you started this year.\n\nWrite 25–35 words.", 35, "A2 Key writing."],
]);

const speaking = speakingsFromRows([
  ["School life", "Compare learning at school and learning online. Which do you prefer?", 15, 60],
  ["Role model", "Describe someone you admire. What have they achieved?", 15, 60],
  ["Technology", "How do you use technology for homework and hobbies?", 15, 60],
  ["Travel", "Tell me about an interesting place you visited.", 15, 60],
  ["Future", "What job would you like in the future? Why?", 15, 60],
  ["Environment", "What can young people do to reduce plastic waste?", 15, 60],
  ["Books films", "Do you prefer reading books or watching films? Why?", 15, 60],
  ["Friends", "What makes a good friend?", 15, 60],
  ["Sports", "Describe a sport or game you enjoy playing.", 15, 60],
  ["English", "Why are you learning English? How do you practise?", 15, 60],
]);

export const KET_SUPPLEMENT: LevelSupplement = {
  reading,
  listening: listeningFromRows(KET_LISTENING_ROWS),
  writing,
  speaking,
  uoe,
};
