import type { LevelSupplement } from "./merge";
import { gapsFromRows, listeningFromRows, readingFromSets, speakingsFromRows, writingsFromRows } from "./helpers";
import { PET_LISTENING_ROWS } from "./data/pet-listening";

const reading = readingFromSets([
  {
    title: "Urban garden",
    passage: "City volunteers turned an empty plot into a shared vegetable garden. Schools help water plants on Wednesdays. Produce is donated to a food bank each month.",
    questions: [
      { question: "What was the plot before?", options: ["A shop","Empty","A road","A lake"], answer: "Empty" },
      { question: "Who helps water plants?", options: ["Schools","Tourists","Drivers","Nobody"], answer: "Schools" },
      { question: "When do schools help?", options: ["Mondays","Wednesdays","Fridays","Sundays"], answer: "Wednesdays" },
      { question: "Where is produce donated?", options: ["A food bank","A stadium","Abroad","Online"], answer: "A food bank" },
      { question: "How often is produce donated?", options: ["Daily","Each month","Never","Every hour"], answer: "Each month" },
    ],
  },
  {
    title: "Podcast launch",
    passage: "Students launched a podcast about teenage entrepreneurs. Episodes include interviews and tips for starting small businesses. Downloads passed one thousand in the first month.",
    questions: [
      { question: "What is the podcast about?", options: ["Sports only","Teenage entrepreneurs","Cooking","History only"], answer: "Teenage entrepreneurs" },
      { question: "What do episodes include?", options: ["Interviews and tips","Only music","Exam papers","Recipes only"], answer: "Interviews and tips" },
      { question: "How many downloads in the first month?", options: ["One hundred","Over one thousand","Ten","None"], answer: "Over one thousand" },
      { question: "Who launched it?", options: ["Teachers","Students","The mayor","Parents only"], answer: "Students" },
      { question: "What businesses are discussed?", options: ["Large factories","Small businesses","Only farms","Only apps"], answer: "Small businesses" },
    ],
  },
]);

const uoe = gapsFromRows([
  ["Tom avoided", "Tom avoided ___ (answer) questions about photography.", "answering"],
  ["The environment prize", "The environment prize ___ (award) last night.", "was awarded"],
  ["I'd rather", "I'd rather ___ (learn) physics than watch TV.", "learn"],
  ["Lily apologised", "Lily apologised ___ breaking the archaeology equipment.", "for"],
  ["Sara denied", "Sara denied ___ (break) the photography equipment.", "breaking"],
  ["The journalism talk", "The journalism talk ___ (give) by Olivia yesterday.", "was given"],
  ["I wish I", "I wish I ___ (know) more about physics.", "knew"],
  ["Leo suggested", "Leo suggested ___ (visit) the beach.", "visiting"],
  ["Hardly", "Hardly ___ Daniel arrived when the class started.", "had"],
  ["Grammar 10", "You ___ (not forget) to bring your space notes.", "mustn't forget"],
  ["The library", "The library ___ (renovate) at the moment.", "is being renovated"],
  ["Lucas is keen", "Lucas is keen ___ learning about poetry.", "on"],
  ["Sophie avoided", "Sophie avoided ___ (answer) questions about gardening.", "answering"],
  ["The weather prize", "The weather prize ___ (award) last night.", "was awarded"],
  ["I'd rather", "I'd rather ___ (learn) astronomy than watch TV.", "learn"],
  ["Minh apologised", "Minh apologised ___ breaking the history equipment.", "for"],
  ["Lan denied", "Lan denied ___ (break) the gardening equipment.", "breaking"],
  ["The medicine talk", "The medicine talk ___ (give) by Ben yesterday.", "was given"],
  ["I wish I", "I wish I ___ (know) more about astronomy.", "knew"],
  ["An suggested", "An suggested ___ (visit) the park.", "visiting"],
  ["Hardly", "Hardly ___ Jack arrived when the class started.", "had"],
  ["Grammar 22", "You ___ (not forget) to bring your theatre notes.", "mustn't forget"],
  ["The café", "The café ___ (renovate) at the moment.", "is being renovated"],
  ["Lily is keen", "Lily is keen ___ learning about marketing.", "on"],
  ["Sara avoided", "Sara avoided ___ (answer) questions about architecture.", "answering"],
  ["The geography prize", "The geography prize ___ (award) last night.", "was awarded"],
  ["I'd rather", "I'd rather ___ (learn) science than watch TV.", "learn"],
  ["Leo apologised", "Leo apologised ___ breaking the languages equipment.", "for"],
  ["Mia denied", "Mia denied ___ (break) the architecture equipment.", "breaking"],
  ["The football talk", "The football talk ___ (give) by Chloe yesterday.", "was given"],
  ["I wish I", "I wish I ___ (know) more about science.", "knew"],
  ["Lucas suggested", "Lucas suggested ___ (visit) the supermarket.", "visiting"],
  ["Hardly", "Hardly ___ Huy arrived when the class started.", "had"],
  ["Grammar 34", "You ___ (not forget) to bring your nutrition notes.", "mustn't forget"],
  ["The airport", "The airport ___ (renovate) at the moment.", "is being renovated"],
  ["Minh is keen", "Minh is keen ___ learning about environment.", "on"],
  ["Lan avoided", "Lan avoided ___ (answer) questions about law.", "answering"],
  ["The archaeology prize", "The archaeology prize ___ (award) last night.", "was awarded"],
  ["I'd rather", "I'd rather ___ (learn) films than watch TV.", "learn"],
  ["An apologised", "An apologised ___ breaking the biology equipment.", "for"],
  ["Tom denied", "Tom denied ___ (break) the law equipment.", "breaking"],
  ["The swimming talk", "The swimming talk ___ (give) by Emma yesterday.", "was given"],
  ["I wish I", "I wish I ___ (know) more about films.", "knew"],
  ["Lily suggested", "Lily suggested ___ (visit) the station.", "visiting"],
  ["Hardly", "Hardly ___ Noah arrived when the class started.", "had"],
  ["Grammar 46", "You ___ (not forget) to bring your technology notes.", "mustn't forget"],
  ["The cinema", "The cinema ___ (renovate) at the moment.", "is being renovated"],
  ["Leo is keen", "Leo is keen ___ learning about weather.", "on"],
  ["Mia avoided", "Mia avoided ___ (answer) questions about music.", "answering"],
  ["The history prize", "The history prize ___ (award) last night.", "was awarded"],
  ["I'd rather", "I'd rather ___ (learn) economics than watch TV.", "learn"],
  ["Lucas apologised", "Lucas apologised ___ breaking the sociology equipment.", "for"],
  ["Sophie denied", "Sophie denied ___ (break) the music equipment.", "breaking"],
  ["The fashion talk", "The fashion talk ___ (give) by Linh yesterday.", "was given"],
  ["I wish I", "I wish I ___ (know) more about economics.", "knew"],
  ["Minh suggested", "Minh suggested ___ (visit) the hospital.", "visiting"],
  ["Hardly", "Hardly ___ Anna arrived when the class started.", "had"],
  ["Grammar 58", "You ___ (not forget) to bring your festivals notes.", "mustn't forget"],
  ["The zoo", "The zoo ___ (renovate) at the moment.", "is being renovated"],
  ["An is keen", "An is keen ___ learning about geography.", "on"],
  ["Tom avoided", "Tom avoided ___ (answer) questions about drama.", "answering"],
  ["The languages prize", "The languages prize ___ (award) last night.", "was awarded"],
  ["I'd rather", "I'd rather ___ (learn) psychology than watch TV.", "learn"],
  ["Lily apologised", "Lily apologised ___ breaking the volunteering equipment.", "for"],
  ["Sara denied", "Sara denied ___ (break) the drama equipment.", "breaking"],
  ["The design talk", "The design talk ___ (give) by Olivia yesterday.", "was given"],
  ["I wish I", "I wish I ___ (know) more about psychology.", "knew"],
  ["Grammar 68", "You ___ (not forget) to bring your literature notes.", "mustn't forget"],
  ["Lucas is keen", "Lucas is keen ___ learning about archaeology.", "on"],
  ["Sophie avoided", "Sophie avoided ___ (answer) questions about debate.", "answering"],
]);

const writing = writingsFromRows([
  ["Story start", "Write a story that begins: 'When I opened the door, I couldn't believe my eyes.'\n\nWrite 100 words.", 100, "B1 Preliminary writing."],
  ["Blog post", "Write a blog post about a club you enjoy.\n\nWrite 100 words.", 100, "B1 Preliminary writing."],
  ["Email plans", "Write an email to a friend about plans for next month.\n\nWrite 100 words.", 100, "B1 Preliminary writing."],
  ["Opinion", "Write about whether students should wear uniform.\n\nWrite 100 words.", 100, "B1 Preliminary writing."],
  ["Trip report", "Write about a school trip you enjoyed.\n\nWrite 100 words.", 100, "B1 Preliminary writing."],
  ["Film message", "Write a message recommending a film to a friend.\n\nWrite 100 words.", 100, "B1 Preliminary writing."],
  ["Environment", "Write about one thing your school does to help the environment.\n\nWrite 100 words.", 100, "B1 Preliminary writing."],
  ["Competition", "Write about a competition you entered.\n\nWrite 100 words.", 100, "B1 Preliminary writing."],
  ["Invitation reply", "Reply to an invitation. You can come but will be late.\n\nWrite 100 words.", 100, "B1 Preliminary writing."],
  ["New hobby", "Write about a new hobby you started this year.\n\nWrite 100 words.", 100, "B1 Preliminary writing."],
]);

const speaking = speakingsFromRows([
  ["School life", "Compare learning at school and learning online. Which do you prefer?", 15, 90],
  ["Role model", "Describe someone you admire. What have they achieved?", 15, 90],
  ["Technology", "How do you use technology for homework and hobbies?", 15, 90],
  ["Travel", "Tell me about an interesting place you visited.", 15, 90],
  ["Future", "What job would you like in the future? Why?", 15, 90],
  ["Environment", "What can young people do to reduce plastic waste?", 15, 90],
  ["Books films", "Do you prefer reading books or watching films? Why?", 15, 90],
  ["Friends", "What makes a good friend?", 15, 90],
  ["Sports", "Describe a sport or game you enjoy playing.", 15, 90],
  ["English", "Why are you learning English? How do you practise?", 15, 90],
]);

export const PET_SUPPLEMENT: LevelSupplement = {
  reading,
  listening: listeningFromRows(PET_LISTENING_ROWS),
  writing,
  speaking,
  uoe,
};
